export enum BOOKING_STATUS {
    // Normal Flow
    CREATED = "CREATED",
    PAID = "PAID",
    REQUESTED = "REQUESTED",
    ACCEPTED = "ACCEPTED",
    IN_PROGRESS = "IN_PROGRESS",
    COMPLETED_BY_PROVIDER = "COMPLETED_BY_PROVIDER",
    CONFIRMED_BY_CLIENT = "CONFIRMED_BY_CLIENT",
    SETTLED = "SETTLED",
    AUTO_SETTLED = "AUTO_SETTLED",
    
    // Exception states
    DECLINED = "DECLINED",
    EXPIRED = "EXPIRED",
    CANCELLED = "CANCELLED",
    DISPUTED = "DISPUTED",
    REFUNDED = "REFUNDED"
}
