export enum BOOKING_STATUS {
  CREATED = 'CREATED',
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED_BY_PROVIDER ='COMPLETED_BY_PROVIDER',
  CONFIRMED_BY_CLIENT = 'CONFIRMED_BY_CLIENT',
  SETTLED = 'SETTLED',
  AUTO_SETTLED = 'AUTO_SETTLED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

