export enum PAYMENT_STATUS {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
  PAID = 'PAID',
  PROVIDER_CANCELLED = 'PROVIDER_CANCELLED',
  WITHDRAWN = 'WITHDRAWN',
  AUTO_SETTLED = 'AUTO_SETTLED',
  CLIENT_CANCELLATION_FEE = 'CLIENT_CANCELLATION_FEE',
}

export enum PAYMENT_TYPE {
  SERVICE_PAYMENT = 'SERVICE_PAYMENT',
  CANCELLATION_REFUND = 'CANCELLATION_REFUND',
  WITHDRAWAL = 'WITHDRAWAL',
  SETTLEMENT = 'SETTLEMENT',
  DISPUTE_REFUND = 'DISPUTE_REFUND',
}

export enum SETTLEMENT_TYPE {
  AUTO = 'AUTO',
  MANUAL = 'MANUAL',
}
